In [1]:
import sqlite3 as sql
import pandas as pd

#crear conecciones y cerrarlas (Mucho Muy Importante)

con = sql.connect("casas.db")
con.close()

In [2]:
#Sí quiero seleccionar todas las columnas de una tabla.

route = "casas.db"
querry = "SELECT * FROM casas;"

con = sql.connect(route)
df = pd.read_sql_query(querry, con)
con.close()

df

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
1,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010
2,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
3,4,Ruta 40 Km 15,4,4,200000.0,180,5,3,1,1,2018
4,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998

In [3]:
#Sí quiero seleccionar una columna en específico.

querry = "SELECT precio FROM casas;"

con = sql.connect(route)
pd.read_sql_query(querry, con)

     precio
0  120000.0
1   95000.0
2  150000.0
3  200000.0
4  110000.0

In [4]:
#Sí quiero seleccionar mas de una columna.

querry = "SELECT direccion, precio FROM casas;"

con = sql.connect(route)
pd.read_sql_query(querry, con)

              direccion    precio
0  Av. Siempre Viva 742  120000.0
1       Calle Falsa 123   95000.0
2      Bv. San Juan 450  150000.0
3         Ruta 40 Km 15  200000.0
4   Av. Pellegrini 2100  110000.0

In [5]:
#Sí quiero seleccionar una columna con un alias.

querry = "SELECT direccion AS lugar  FROM casas;"

con = sql.connect(route)
pd.read_sql_query(querry, con)

                  lugar
0  Av. Siempre Viva 742
1       Calle Falsa 123
2      Bv. San Juan 450
3         Ruta 40 Km 15
4   Av. Pellegrini 2100

In [6]:
#Sí quiero seleccionar una columna con un alias descriptivo.

querry = "SELECT direccion AS 'lugar de residencia'  FROM casas;"

con = sql.connect(route)
pd.read_sql_query(querry, con)

    lugar de residencia
0  Av. Siempre Viva 742
1       Calle Falsa 123
2      Bv. San Juan 450
3         Ruta 40 Km 15
4   Av. Pellegrini 2100

In [7]:
con.close()