In [1]:
import sqlite3 as sql
import pandas as pd

con = sql.connect("casas.db")
con.close()

In [2]:
#Con la clausula WHERE, podemos filtrar registros en la consulta.

route = "casas.db"
querry = "SELECT * FROM casas WHERE precio > 100000;"

con = sql.connect(route)

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
1,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
2,4,Ruta 40 Km 15,4,4,200000.0,180,5,3,1,1,2018
3,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998

In [3]:
#Todo comparador matemático es compatible.

querry = "SELECT * FROM casas WHERE precio <= 100000;"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010

In [4]:
#Se pueden mezclar fiiltros de columnas y campos.

querry = "SELECT direccion, precio FROM casas WHERE precio > 100000;"

pd.read_sql_query(querry, con)

              direccion    precio
0  Av. Siempre Viva 742  120000.0
1      Bv. San Juan 450  150000.0
2         Ruta 40 Km 15  200000.0
3   Av. Pellegrini 2100  110000.0

In [5]:
#Se pueden obtener datos concretos con estos filtros.

querry = "SELECT direccion FROM casas WHERE id_casa = 2;"

pd.read_sql_query(querry, con)

         direccion
0  Calle Falsa 123

In [6]:
#Se puede filtrar por comparación de texto.

querry = "SELECT * FROM casas WHERE direccion = 'Calle Falsa 123';"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010

In [7]:
#Se puede filtrar también por valores booleanos.

querry = "SELECT * FROM casas WHERE disponibilidad = TRUE;"

#Mi base de datos no cuenta con valores booleanos pero confia en que es así como se usa.

In [8]:
#Se pueden fortalecer las claúsulas con operadores lógicos.

querry = "SELECT * FROM casas WHERE precio > 10 AND habitaciones < 3;"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010

In [9]:
#Uso del OR.

querry = "SELECT * FROM casas WHERE precio > 100000 OR habitaciones = 2;"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
1,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010
2,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
3,4,Ruta 40 Km 15,4,4,200000.0,180,5,3,1,1,2018
4,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998

In [10]:
#Utilizando el tipo de dato 'date'.

querry = "SELECT * FROM casas WHERE fecha_de_construccion < '2022-12-31'"

#Vos confia que así se usa, es primero el año, despues el mes y por último el día.

In [11]:
#Se puede usar tambien el operador BETWEEN que agarra valores entre 2 varemos.

querry = "SELECT * FROM casas WHERE precio BETWEEN 10 AND 150000"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
1,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010
2,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
3,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998

In [12]:
#Existe tambien la claúsula LIKE, que compara por caracteres coincidentes.

querry = "SELECT * FROM casas WHERE direccion LIKE 'A%'"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
1,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998

In [13]:
#Con el comodín (%) por delante, podemos filtrar por terminación.

querry = "SELECT * FROM casas WHERE direccion LIKE '%0'"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
1,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998

In [14]:
#También podemos filtrar si no queremos los valores nulos de alguna columna en particular.

querry = "SELECT * FROM casas WHERE direccion IS NOT NULL"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
1,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010
2,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
3,4,Ruta 40 Km 15,4,4,200000.0,180,5,3,1,1,2018
4,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998

In [15]:
#Así mismo, podemos también filtrar por columnas que si tengan null.

querry = "SELECT * FROM casas WHERE direccion IS NULL"

pd.read_sql_query(querry, con)

Empty DataFrame
Columns: [id_casa, direccion, id_ciudad, id_propietario, precio, metros_cuadrados, habitaciones, banos, tiene_garaje, tiene_patio, anio_construccion]
Index: []

In [16]:
con.close()