In [1]:
import sqlite3 as sql
import pandas as pd

con = sql.connect("casas.db")
con.close()

In [2]:
#ORDER BY ordena por defecto en orden ascendente

con = sql.connect("casas.db")
querry = "SELECT * FROM casas ORDER BY precio;"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010
1,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998
2,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
3,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
4,4,Ruta 40 Km 15,4,4,200000.0,180,5,3,1,1,2018

In [3]:
#Implicitamente podemos pedir que se ordenen de manera ascendente.

querry = "SELECT * FROM casas ORDER BY precio ASC;"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010
1,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998
2,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
3,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
4,4,Ruta 40 Km 15,4,4,200000.0,180,5,3,1,1,2018

In [4]:
#Así mismo, se puede pedir en orden descendente.

querry = "SELECT * FROM casas ORDER BY precio DESC"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,4,Ruta 40 Km 15,4,4,200000.0,180,5,3,1,1,2018
1,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
2,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
3,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998
4,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010

In [5]:
#Los campos nulos tiene el valor mas bajo, por lo que ordenar de manera ascendente los pondrá en los primeros de la lista.
#Podemos especificar tambien si los queremos primeros o ultimos con la orden NULLS FIRST o NULLS LAST

querry = "SELECT * FROM casas ORDER BY precio NULLS LAST;"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010
1,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998
2,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
3,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
4,4,Ruta 40 Km 15,4,4,200000.0,180,5,3,1,1,2018

In [6]:
#Se puede también ordenar por más de una cosa a la vez.

querry = "SELECT * FROM casas ORDER BY id_ciudad ASC, precio ASC;"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010
1,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
2,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
3,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998
4,4,Ruta 40 Km 15,4,4,200000.0,180,5,3,1,1,2018

In [7]:
#Podemos convinarlo con otras consultas respetando las gerarquías.

querry = "SELECT * FROM casas WHERE precio >= 100000 ORDER BY id_ciudad ASC, precio ASC;"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
1,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
2,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998
3,4,Ruta 40 Km 15,4,4,200000.0,180,5,3,1,1,2018

In [8]:
con.close()