In [1]:
import sqlite3 as sql
import pandas as pd

con = sql.connect("casas.db")
con.close()

In [2]:
#Manipular los strings de la consulta suele tener alguna útilidad.

con = sql.connect("casas.db")
querry = "SELECT UPPER(direccion) FROM casas;"

pd.read_sql_query(querry, con)

       UPPER(direccion)
0  AV. SIEMPRE VIVA 742
1       CALLE FALSA 123
2      BV. SAN JUAN 450
3         RUTA 40 KM 15
4   AV. PELLEGRINI 2100

In [3]:
#Así como existe upper, también esta lower.

querry = "SELECT LOWER(direccion) FROM casas;"

pd.read_sql_query(querry, con)

       LOWER(direccion)
0  av. siempre viva 742
1       calle falsa 123
2      bv. san juan 450
3         ruta 40 km 15
4   av. pellegrini 2100

In [4]:
#Para elimiar los espacios del inicio y final de un string poder usar la funcion TRIM.

querry = "SELECT TRIM(direccion) FROM casas;"

pd.read_sql_query(querry,con)

        TRIM(direccion)
0  Av. Siempre Viva 742
1       Calle Falsa 123
2      Bv. San Juan 450
3         Ruta 40 Km 15
4   Av. Pellegrini 2100

In [5]:
#Estos comandos son iterables, por lo que se pueden llamar simultaneamente.

querry = "SELECT TRIM(LOWER(direccion)) AS direccion_limpia FROM casas;"

pd.read_sql_query(querry,con)

       direccion_limpia
0  av. siempre viva 742
1       calle falsa 123
2      bv. san juan 450
3         ruta 40 km 15
4   av. pellegrini 2100

In [6]:
#LENGTH nos sirve par aver el tamaño del string en la columna seleccionada.

querry = "SELECT direccion, LENGTH(direccion) AS dir_len FROM casas ORDER BY dir_len DESC LIMIT 3;"

pd.read_sql_query(querry,con)

              direccion  dir_len
0  Av. Siempre Viva 742       20
1   Av. Pellegrini 2100       19
2      Bv. San Juan 450       16

In [7]:
#El operador concatenar lleva un ' ' con las cuales indicas el separador de la concatenación.

querry = "SELECT precio || '-' || anio_construccion AS valor_por_antiguedad FROM casas;"

pd.read_sql_query(querry, con)

  valor_por_antiguedad
0        120000.0-2005
1         95000.0-2010
2        150000.0-2000
3        200000.0-2018
4        110000.0-1998

In [8]:
#El método SUBSTR() nos permite hacer una sub-sequiencia de caracteres a partir de un string. El primer parámetro es el nombre de la columna, 
#el segundo el incio, y el último es la longitud.

querry = "SELECT SUBSTR(nombre, 1, 1) AS inciales_vendedor FROM propietarios;"

pd.read_sql_query(querry, con)

  inciales_vendedor
0                 J
1                 M
2                 L
3                 A

In [9]:
con.close()