In [1]:
import sqlite3 as sql
import pandas as pd

con = sql.connect("casas.db")
con.close()

In [3]:
#Con GROUP BY podemos agrupar valores unicos de una columna. 

route = "casas.db"
con = sql.connect(route)

querry = """
        SELECT habitaciones
        FROM casas
        GROUP BY habitaciones;
        """

df = pd.read_sql_query(querry, con)

df

   habitaciones
0             2
1             3
2             4
3             5

In [ ]:
#Es muy útil para usarse con funciones de agregación.

querry = """
        SELECT pais, 
        COUNT(*) AS cantidad_de_ciudades
        FROM ciudades
        GROUP BY pais;
        """
df = pd.read_sql_query(querry, con)

df

        pais  cantidad_de_ciudades
0  Argentina                     4

In [ ]:
#El orden de gerarquia es FROM -> WHERE -> GROUP BY.

query = """
        SELECT id_ciudad,
        MAX(precio) AS mas_cara
        FROM casas
        GROUP BY id_ciudad;
        """
df = pd.read_sql_query(query, con)

df

   id_ciudad  mas_cara
0          1  120000.0
1          2  150000.0
2          3  110000.0
3          4  200000.0

In [4]:
#la seleccion de grupos puede simplicarse con llamar a las columnas por su posicion en la consulta.

query = """
        SELECT id_ciudad,
        MAX(precio) AS mas_cara
        FROM casas
        GROUP BY 1;
        """

df = pd.read_sql_query(query, con)

con.close()
df

   id_ciudad  mas_cara
0          1  120000.0
1          2  150000.0
2          3  110000.0
3          4  200000.0

In [ ]:
#La cluasula HAVING se utiliza como un filtro que se utiliza en la agrupación (parecido al WHERE).

con = sql.connect("casas.db")

query = """
        SELECT id_ciudad,
        COUNT(*) AS cantidad_casas
        FROM casas
        GROUP BY id_ciudad
        HAVING cantidad_casas > 1;
        """

df = pd.read_sql_query(query, con)

df

In [ ]:
#La gerarquia sobre el HAVING se aplica a la que ya teniamos SELECT -> FROM -> WHERE -> GROUP BY -> HAVING -> ORDER BY

query = """
        SELECT id_ciudad,
        COUNT(*) AS cantidad_casas
        FROM casas
        WHERE precio > 100000
        GROUP BY id_ciudad
        HAVING cantidad_casas >= 1
        ORDER BY cantidad_casas DESC;
        """

df = pd.read_sql_query(query, con)

con.close()
df